# Generated by Django 5.1.7 on 2026-08-26 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("mobility", "Mobility"),
                            ("falls", "Falls Risk"),
                            ("nutrition", "Nutrition"),
                            ("pain", "Pain"),
                            ("skin", "Skin"),
                            ("cognitive", "Cognitive"),
                            ("behavioural", "Behavioural"),
                        ],
                        max_length=30,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("result", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("next_review", models.DateField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="residents.resident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                ("next_review", models.DateField(blank=True, null=True)),
                ("mobility", models.TextField(blank=True)),
                ("nutrition", models.TextField(blank=True)),
                ("personal_care", models.TextField(blank=True)),
                ("communication", models.TextField(blank=True)),
                ("cognitive_support", models.TextField(blank=True)),
                ("behavioural_support", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_care_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_plans",
                        to="residents.resident",
                    ),
                ),
                (
                    "responsible_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_care_plans",
                        to="staff.staffmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveBehaviouralSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_requirements", models.TextField(blank=True)),
                ("known_triggers", models.TextField(blank=True)),
                ("communication_preferences", models.TextField(blank=True)),
                ("behaviour_observations", models.TextField(blank=True)),
                ("de_escalation_strategies", models.TextField(blank=True)),
                ("care_instructions", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_support",
                        to="residents.resident",
                    ),
                ),
            ],
        ),
    ]
