# Generated by Django 5.1.7 on 2026-08-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("admission_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hospital", "Hospital"),
                            ("leave", "On Leave"),
                            ("discharged", "Discharged"),
                            ("deceased", "Deceased"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "care_level",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("high", "High"),
                            ("complex", "Complex"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("mobility_needs", models.TextField(blank=True)),
                ("nutrition_needs", models.TextField(blank=True)),
                ("communication_needs", models.TextField(blank=True)),
                ("cognitive_support_needs", models.TextField(blank=True)),
                ("behavioural_support_needs", models.TextField(blank=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="facility.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResidentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency Contact"),
                            ("family", "Family / Representative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("relationship", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="residents.resident",
                    ),
                ),
            ],
        ),
    ]
